class RefCount:
    def add_state(self, eid: int, xid: int) -> int: ...
    def load_state(self, xid: int) -> int: ...
    def has_xid(self, xid: int) -> bool: ...
    def remove_transition(self, eid: int) -> None: ...
